/// Grain: one row per state x year x crime head. Filtered to include_in_analysis.
table FactCrimes
	lineageTag: 2c1f0a10-0001-4a00-9000-000000000001

	measure 'Total Cases' = SUM ( FactCrimes[cases] )
		formatString: #,0
		lineageTag: 2c1f0a10-0002-4a00-9000-000000000002

	measure 'DV Cases' = CALCULATE ( [Total Cases], DimCrimeType[Crime Code] = "DV" )
		formatString: #,0
		lineageTag: 2c1f0a10-0003-4a00-9000-000000000003

	measure 'All Crime Cases' = CALCULATE ( [Total Cases], REMOVEFILTERS ( DimCrimeType ) )
		formatString: #,0
		lineageTag: 2c1f0a10-0004-4a00-9000-000000000004

	/// Blank when every visible year is non-comparable - i.e. when 2011 is selected on
	/// its own. Assault on Women is missing from the source that year, so an all-crime
	/// denominator for 2011 alone is ~40,000 cases short and prints a false ~55% spike
	/// against a 39.2% baseline. The guard counts COMPARABLE years rather than
	/// non-comparable ones: counting non-comparable years also blanked the 21-year
	/// total, because 2011 sits inside it, which suppressed the headline figure.
	measure 'DV Share %' =
			VAR ComparableYears =
				CALCULATE ( COUNTROWS ( DimYear ), DimYear[All Crimes Comparable] = TRUE () )
			RETURN
				IF ( COALESCE ( ComparableYears, 0 ) > 0, DIVIDE ( [DV Cases], [All Crime Cases] ) )
		formatString: 0.0%
		lineageTag: 2c1f0a10-0005-4a00-9000-000000000005

	measure 'States Reporting' = CALCULATE ( DISTINCTCOUNT ( FactCrimes[state_clean] ) )
		formatString: #,0
		lineageTag: 2c1f0a10-0006-4a00-9000-000000000006

	measure 'Years Covered' = CALCULATE ( DISTINCTCOUNT ( FactCrimes[year] ) )
		formatString: #,0
		lineageTag: 2c1f0a10-0007-4a00-9000-000000000007

	/// Row count at the current grain. Used on the data-quality page to show how many
	/// cells each quality flag accounts for.
	measure 'Fact Rows' = COUNTROWS ( FactCrimes )
		formatString: #,0
		lineageTag: 2c1f0a10-0025-4a00-9000-000000000025

	measure 'DV Cases PY' =
			VAR Y = SELECTEDVALUE ( DimYear[Year] )
			RETURN
				IF ( NOT ISBLANK ( Y ),
					CALCULATE ( [DV Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = Y - 1 ) ) )
		formatString: #,0
		lineageTag: 2c1f0a10-0008-4a00-9000-000000000008

	measure 'DV YoY %' = DIVIDE ( [DV Cases] - [DV Cases PY], [DV Cases PY] )
		formatString: +0.0%;-0.0%;0.0%
		lineageTag: 2c1f0a10-0009-4a00-9000-000000000009

	measure 'DV 3Y Moving Avg' =
			VAR Y = SELECTEDVALUE ( DimYear[Year] )
			RETURN
				IF ( NOT ISBLANK ( Y ),
					CALCULATE (
						AVERAGEX ( VALUES ( DimYear[Year] ), [DV Cases] ),
						FILTER ( ALL ( DimYear[Year] ), DimYear[Year] >= Y - 2 && DimYear[Year] <= Y )
					) )
		formatString: #,0
		lineageTag: 2c1f0a10-000a-4a00-9000-00000000000a

	/// ALLSELECTED so the growth rate follows the year slicer window.
	measure 'DV CAGR %' =
			VAR VisibleYears = ALLSELECTED ( DimYear[Year] )
			VAR FirstYear = MINX ( VisibleYears, DimYear[Year] )
			VAR LastYear = MAXX ( VisibleYears, DimYear[Year] )
			VAR Periods = LastYear - FirstYear
			VAR FirstValue = CALCULATE ( [DV Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = FirstYear ) )
			VAR LastValue = CALCULATE ( [DV Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = LastYear ) )
			RETURN
				IF ( Periods > 0 && FirstValue > 0, ( DIVIDE ( LastValue, FirstValue ) ^ DIVIDE ( 1, Periods ) ) - 1 )
		formatString: 0.00%
		lineageTag: 2c1f0a10-000b-4a00-9000-00000000000b

	/// Generic index over Total Cases, so it responds to whatever dimension is on the
	/// legend. The DV-specific version below hardcodes [DV Cases] and therefore draws a
	/// single line when crime type is the series - correct for a DV-only chart, useless
	/// for comparing heads.
	measure 'Index (Base = 100)' =
			VAR BaseYear = CALCULATE ( MIN ( DimYear[Year] ), ALLSELECTED ( DimYear ) )
			VAR BaseValue = CALCULATE ( [Total Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = BaseYear ) )
			RETURN DIVIDE ( [Total Cases], BaseValue ) * 100
		formatString: #,0
		lineageTag: 2c1f0a10-0030-4a00-9000-000000000030

	/// Generic CAGR over Total Cases. Replaces binding a chart straight to the ETL's
	/// stored cagr_pct column: that column is summarizeBy none (correct - averaging a
	/// growth rate across heads is meaningless), which left the bar chart empty because
	/// a chart axis needs something it is allowed to aggregate. A measure is the right
	/// answer anyway, since it recomputes inside the year slicer.
	measure 'CAGR %' =
			VAR VisibleYears = ALLSELECTED ( DimYear[Year] )
			VAR FirstYear = MINX ( VisibleYears, DimYear[Year] )
			VAR LastYear = MAXX ( VisibleYears, DimYear[Year] )
			VAR Periods = LastYear - FirstYear
			VAR FirstValue = CALCULATE ( [Total Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = FirstYear ) )
			VAR LastValue = CALCULATE ( [Total Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = LastYear ) )
			RETURN
				IF ( Periods > 0 && FirstValue > 0, ( DIVIDE ( LastValue, FirstValue ) ^ DIVIDE ( 1, Periods ) ) - 1 )
		formatString: 0.00%
		lineageTag: 2c1f0a10-0031-4a00-9000-000000000031

	/// The entity count NCRB itself published that year. MAX, not SUM - it is a
	/// attribute of the year, and the stored column is summarizeBy none so a chart
	/// cannot aggregate it directly.
	measure 'Source Reporting Entities' = MAX ( DimYear[Reporting Entities] )
		formatString: #,0
		lineageTag: 2c1f0a10-0032-4a00-9000-000000000032

	/// Rebases each state to 100 in the first visible year so small states are legible.
	measure 'DV Index (Base = 100)' =
			VAR BaseYear = CALCULATE ( MIN ( DimYear[Year] ), ALLSELECTED ( DimYear ) )
			VAR BaseValue = CALCULATE ( [DV Cases], FILTER ( ALL ( DimYear[Year] ), DimYear[Year] = BaseYear ) )
			RETURN DIVIDE ( [DV Cases], BaseValue ) * 100
		formatString: #,0
		lineageTag: 2c1f0a10-000c-4a00-9000-00000000000c

	measure 'Female Population' = SUMX ( VALUES ( DimState[State] ), CALCULATE ( MAX ( DimState[Female Population 2011] ) ) )
		formatString: #,0
		lineageTag: 2c1f0a10-000d-4a00-9000-00000000000d

	measure 'DV Rate per Lakh Women' = DIVIDE ( [DV Cases], [Female Population] ) * 100000
		formatString: #,0.0
		lineageTag: 2c1f0a10-000e-4a00-9000-00000000000e

	/// Window-safe: divides by years in context so the value stays readable at any slicer width.
	measure 'DV Rate per Lakh Women (Annual Avg)' =
			VAR YearsInContext = DISTINCTCOUNT ( FactCrimes[year] )
			RETURN DIVIDE ( DIVIDE ( [DV Cases], YearsInContext ), [Female Population] ) * 100000
		formatString: #,0.0
		lineageTag: 2c1f0a10-000f-4a00-9000-00000000000f

	measure 'DV Rate vs National' =
			VAR StateRate = [DV Rate per Lakh Women]
			VAR NationalRate = CALCULATE ( DIVIDE ( [DV Cases], [Female Population] ) * 100000, REMOVEFILTERS ( DimState ) )
			RETURN DIVIDE ( StateRate, NationalRate )
		formatString: 0.00
		lineageTag: 2c1f0a10-0010-4a00-9000-000000000010

	/// Pareto engine: share of national volume carried by states ranked at or above this one.
	measure 'DV Cumulative Share %' =
			VAR CurrentState = SELECTEDVALUE ( DimState[State] )
			VAR CurrentValue = [DV Cases]
			VAR StateTotals = ADDCOLUMNS ( ALLSELECTED ( DimState[State] ), "@dv", CALCULATE ( [DV Cases] ) )
			VAR GrandTotal = SUMX ( StateTotals, [@dv] )
			VAR RunningTotal = SUMX ( FILTER ( StateTotals, [@dv] >= CurrentValue ), [@dv] )
			RETURN
				IF ( NOT ISBLANK ( CurrentState ) && CurrentValue > 0, DIVIDE ( RunningTotal, GrandTotal ) )
		formatString: 0.0%
		lineageTag: 2c1f0a10-0011-4a00-9000-000000000011

	/// Classifies on the cumulative share reached BEFORE this state is added, which puts
	/// the state that crosses the 70% line inside class A rather than outside it.
	///
	/// This matters: banding on the inclusive cumulative (Cum <= 0.70) drops Madhya
	/// Pradesh - whose running total lands on 72.9% - into class B and reports "7 of 36
	/// carry 68.0%". The ETL and the SQL layer both use the exclusive convention and
	/// report "8 of 36 carry 72.9%". Same data, same intent, one boundary rule apart.
	/// The dashboard must not disagree with its own README, so the DAX follows the ETL.
	measure 'ABC Class' =
			VAR StateTotals = ADDCOLUMNS ( ALLSELECTED ( DimState[State] ), "@dv", CALCULATE ( [DV Cases] ) )
			VAR GrandTotal = SUMX ( StateTotals, [@dv] )
			VAR OwnShare = DIVIDE ( [DV Cases], GrandTotal )
			VAR CumulativeBefore = [DV Cumulative Share %] - OwnShare
			RETURN
				SWITCH (
					TRUE (),
					ISBLANK ( [DV Cumulative Share %] ), BLANK (),
					CumulativeBefore < 0.70, "A",
					CumulativeBefore < 0.90, "B",
					"C"
				)
		lineageTag: 2c1f0a10-0012-4a00-9000-000000000012

	measure 'States in Class A' = COUNTROWS ( FILTER ( VALUES ( DimState[State] ), [ABC Class] = "A" ) )
		formatString: #,0
		lineageTag: 2c1f0a10-0013-4a00-9000-000000000013

	measure 'Class A Cases' = SUMX ( FILTER ( VALUES ( DimState[State] ), [ABC Class] = "A" ), [DV Cases] )
		formatString: #,0
		lineageTag: 2c1f0a10-0014-4a00-9000-000000000014

	measure 'Class A Share %' = DIVIDE ( [Class A Cases], CALCULATE ( [DV Cases], REMOVEFILTERS ( DimState ) ) )
		formatString: 0.0%
		lineageTag: 2c1f0a10-0015-4a00-9000-000000000015

	/// Card text that restates the concentration finding for the current slicer state.
	measure 'ABC Headline' =
			VAR N = [States in Class A]
			VAR Share = [Class A Share %]
			VAR Total = COUNTROWS ( ALLSELECTED ( DimState[State] ) )
			RETURN
				IF ( NOT ISBLANK ( N ),
					FORMAT ( N, "0" ) & " of " & FORMAT ( Total, "0" ) & " entities carry "
						& FORMAT ( Share, "0.0%" ) )
		lineageTag: 2c1f0a10-0016-4a00-9000-000000000016

	measure 'Risk Threshold Moderate' = 2.5
		formatString: #,0.0
		lineageTag: 2c1f0a10-0017-4a00-9000-000000000017

	measure 'Risk Threshold High' = 9.1
		formatString: #,0.0
		lineageTag: 2c1f0a10-0018-4a00-9000-000000000018

	measure 'Risk Threshold Critical' = 22.9
		formatString: #,0.0
		lineageTag: 2c1f0a10-0019-4a00-9000-000000000019

	/// Quartiles of the 2021 rate distribution, from data/processed/risk_thresholds.json.
	measure 'Risk Zone' =
			VAR Rate = [DV Rate per Lakh Women (Annual Avg)]
			RETURN
				SWITCH (
					TRUE (),
					ISBLANK ( Rate ), BLANK (),
					Rate >= [Risk Threshold Critical], "Critical",
					Rate >= [Risk Threshold High], "High",
					Rate >= [Risk Threshold Moderate], "Moderate",
					"Low"
				)
		lineageTag: 2c1f0a10-001a-4a00-9000-00000000001a

	measure 'DV Rank' = IF ( NOT ISBLANK ( [DV Cases] ), RANKX ( ALLSELECTED ( DimState[State] ), [DV Cases], , DESC, DENSE ) )
		formatString: #,0
		lineageTag: 2c1f0a10-001b-4a00-9000-00000000001b

	measure 'DV Rate Rank' =
			IF ( NOT ISBLANK ( [DV Cases] ),
				RANKX ( ALLSELECTED ( DimState[State] ), [DV Rate per Lakh Women (Annual Avg)], , DESC, DENSE ) )
		formatString: #,0
		lineageTag: 2c1f0a10-001c-4a00-9000-00000000001c

	/// Positive means the state is more intense than its case count suggests.
	measure 'Volume vs Intensity Gap' = [DV Rank] - [DV Rate Rank]
		formatString: +0;-0;0
		lineageTag: 2c1f0a10-001d-4a00-9000-00000000001d

	measure 'Priority Segment' =
			VAR Class = [ABC Class]
			VAR Zone = [Risk Zone]
			VAR Growing = [DV CAGR %] > 0
			RETURN
				SWITCH (
					TRUE (),
					ISBLANK ( Class ) || ISBLANK ( Zone ), BLANK (),
					Class = "A" && Zone IN { "Critical", "High" }, "P1 - Scale intervention (high volume, high intensity)",
					Class = "A", "P2 - Sustain capacity (high volume, contained intensity)",
					Zone IN { "Critical", "High" }, "P3 - Targeted intervention (small entity, high intensity)",
					Growing, "P4 - Monitor (low now, rising)",
					"P5 - Maintain"
				)
		lineageTag: 2c1f0a10-001e-4a00-9000-00000000001e

	/// Narrates whichever state is selected, so the deep-dive page explains itself during
	/// a demo instead of needing one hand-written annotation per state.
	///
	/// Always returns a string. The first version returned BLANK when no single state was
	/// selected (SELECTEDVALUE with no default, inside an IF with no else branch) and the
	/// card rendered as an error rather than as empty. SELECTEDVALUE now carries a
	/// default and every branch produces text.
	measure 'State Verdict' =
			VAR St = SELECTEDVALUE ( DimState[State], "" )
			VAR Cases = COALESCE ( [DV Cases], 0 )
			VAR Rate = COALESCE ( [DV Rate per Lakh Women (Annual Avg)], 0 )
			VAR RankVol = COALESCE ( [DV Rank], 0 )
			VAR RankInt = COALESCE ( [DV Rate Rank], 0 )
			RETURN
				IF (
					St = "" || Cases = 0,
					"Select a single state to see its verdict",
					St & ": " & FORMAT ( Cases, "#,0" ) & " cases. Rank " & FORMAT ( RankVol, "0" )
						& " by volume, rank " & FORMAT ( RankInt, "0" ) & " by intensity ("
						& FORMAT ( Rate, "0.0" ) & " per lakh women a year)."
				)
		lineageTag: 2c1f0a10-0026-4a00-9000-000000000026

	measure 'ABC Class Label' =
			SWITCH ( [ABC Class],
				"A", "A - Critical (top 70% of volume)",
				"B", "B - Moderate (next 20%)",
				"C", "C - Low (tail 10%)",
				BLANK () )
		lineageTag: 2c1f0a10-0027-4a00-9000-000000000027

	measure 'DV YoY Cases' = [DV Cases] - [DV Cases PY]
		formatString: +#,0;-#,0;0
		lineageTag: 2c1f0a10-0028-4a00-9000-000000000028

	/// Constant lines for the cumulative axis of the Pareto combo chart.
	measure 'Pareto 70% Line' = 0.70
		formatString: 0%
		lineageTag: 2c1f0a10-0029-4a00-9000-000000000029

	measure 'Pareto 90% Line' = 0.90
		formatString: 0%
		lineageTag: 2c1f0a10-002a-4a00-9000-00000000002a

	/// Numeric companion to [Risk Zone] for conditional formatting and severity sorting.
	measure 'Risk Zone Rank' = SWITCH ( [Risk Zone], "Critical", 1, "High", 2, "Moderate", 3, "Low", 4, 9 )
		formatString: 0
		lineageTag: 2c1f0a10-002b-4a00-9000-00000000002b

	/// Narrates the current filter state back to the viewer so a screenshot of the page
	/// is self-describing when it is pasted into a deck.
	///
	/// Every numeric goes through FORMAT rather than relying on implicit conversion in
	/// the & operator, and every VAR is COALESCEd. A card bound to this measure showed
	/// "Something's wrong with one or more fields" when the year bounds were
	/// concatenated raw; the sibling ABC Headline card, which formats everything
	/// explicitly, rendered fine.
	measure 'Filter Context Label' =
			VAR YearMin = COALESCE ( MIN ( DimYear[Year] ), 0 )
			VAR YearMax = COALESCE ( MAX ( DimYear[Year] ), 0 )
			VAR StateCnt = COALESCE ( [States Reporting], 0 )
			VAR AllStates = COALESCE ( COUNTROWS ( ALL ( DimState[State] ) ), 0 )
			VAR Scope =
				IF ( StateCnt = AllStates, "all India", FORMAT ( StateCnt, "#,0" ) & " entities" )
			RETURN
				"Recorded cases, " & FORMAT ( YearMin, "0" ) & "-" & FORMAT ( YearMax, "0" )
					& ", " & Scope
		lineageTag: 2c1f0a10-001f-4a00-9000-00000000001f

	column state_clean
		dataType: string
		isHidden
		lineageTag: 2c1f0a10-0020-4a00-9000-000000000020
		summarizeBy: none
		sourceColumn: state_clean

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c1f0a10-0021-4a00-9000-000000000021
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column crime_code
		dataType: string
		isHidden
		lineageTag: 2c1f0a10-0022-4a00-9000-000000000022
		summarizeBy: none
		sourceColumn: crime_code

		annotation SummarizationSetBy = Automatic

	column cases
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 2c1f0a10-0023-4a00-9000-000000000023
		summarizeBy: sum
		sourceColumn: cases

		annotation SummarizationSetBy = Automatic

	/// ok | source_gap | entity_not_formed - kept visible for the data-quality page.
	column data_quality_flag
		dataType: string
		lineageTag: 2c1f0a10-0024-4a00-9000-000000000024
		summarizeBy: none
		sourceColumn: data_quality_flag

		annotation SummarizationSetBy = Automatic

	partition FactCrimes = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "\data\processed\fact_crimes_long.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Trimmed = Table.SelectColumns(Promoted, {"state_clean", "year", "crime_code", "cases", "data_quality_flag", "include_in_analysis"}),
					Typed = Table.TransformColumnTypes(Trimmed, {{"state_clean", type text}, {"year", Int64.Type}, {"crime_code", type text}, {"cases", Int64.Type}, {"data_quality_flag", type text}, {"include_in_analysis", type text}}),
					Analysable = Table.SelectRows(Typed, each Text.Lower([include_in_analysis]) = "true"),
					Final = Table.RemoveColumns(Analysable, {"include_in_analysis"})
				in
					Final

	annotation PBI_ResultType = Table

