"""
build_and_run.py
================
Builds the SQLite warehouse from data/processed/, then executes every analytical
.sql file and writes the real results to sql/QUERY_RESULTS.md.

Committing the outputs alongside the queries means a reader can verify a claim in
the README without installing anything, and any drift between the SQL and the
dashboard shows up in a diff.

Run:  python3 sql/build_and_run.py
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SQL = ROOT / "sql"
PROC = ROOT / "data" / "processed"
DB = SQL / "crimes_against_women.db"

# Which processed CSV feeds which table, and the column order the DDL declares.
LOADS = [
    ("dim_state", "dim_state.csv"),
    ("dim_crime_type", "dim_crime_type.csv"),
    ("dim_year", "dim_year.csv"),
    ("fact_crimes", "fact_crimes_long.csv"),
]

ANALYTICAL = [
    ("01_kpi_headline.sql", "Headline KPIs"),
    ("02_trend_window_functions.sql", "Trend, YoY, CAGR and momentum"),
    ("03_abc_classification.sql", "ABC / Pareto classification"),
    ("04_risk_zones_case.sql", "Risk zones and priority matrix"),
    ("05_joins_deepdive.sql", "Multi-table joins and deep dives"),
]

MAX_ROWS = 40   # keep the committed report readable


def build() -> sqlite3.Connection:
    if DB.exists():
        DB.unlink()
    con = sqlite3.connect(DB)
    con.executescript((SQL / "00_schema.sql").read_text())

    for table, csv_name in LOADS:
        df = pd.read_csv(PROC / csv_name)
        cols = [r[1] for r in con.execute(f"PRAGMA table_info({table})")]
        if table == "fact_crimes":
            cols = [c for c in cols if c != "fact_id"]     # AUTOINCREMENT
        missing = [c for c in cols if c not in df.columns]
        if missing:
            raise SystemExit(f"{table}: processed CSV is missing {missing}")
        df["is_structural_zero"] = df.get("is_structural_zero", False)
        for boolcol in ("is_structural_zero", "is_focus_crime", "is_covid_year"):
            if boolcol in df.columns:
                df[boolcol] = df[boolcol].astype(bool).astype(int)
        df[cols].to_sql(table, con, if_exists="append", index=False)
        n = con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        print(f"  loaded {table:<16s} {n:>5} rows")

    con.commit()
    return con


def split_statements(text: str) -> list[tuple[str, str]]:
    """Split a .sql file into (header_comment, statement) pairs.

    Header = the '-- Qx.y ...' banner immediately above the statement, which is
    what gives each result block a title in the report.
    """
    out = []
    for raw in text.split(";\n"):
        stmt = raw.strip()
        if not stmt or all(l.strip().startswith("--") or not l.strip()
                           for l in stmt.splitlines()):
            continue
        title = ""
        for line in stmt.splitlines():
            m = re.match(r"^--\s*(Q\d+\.\d+\s+.*)$", line.strip())
            if m:
                title = m.group(1).strip()
                break
        out.append((title, stmt))
    return out


def run_reports(con: sqlite3.Connection) -> None:
    md = [
        "# SQL Query Results",
        "",
        "Generated by `sql/build_and_run.py` against `sql/crimes_against_women.db`,",
        "which is built from `data/processed/` by `etl/01_clean_and_wrangle.py`.",
        "",
        "Every number quoted in the README and in `docs/INSIGHTS.md` can be traced",
        f"to a query below. Result sets are truncated to {MAX_ROWS} rows for readability;",
        "run the query yourself for the full output.",
        "",
        "---",
        "",
    ]

    for filename, section in ANALYTICAL:
        md += [f"## {filename} - {section}", ""]
        print(f"\n>>> {filename}")
        for title, stmt in split_statements((SQL / filename).read_text()):
            label = title or "(query)"
            print(f"    {label}")
            try:
                df = pd.read_sql_query(stmt, con)
            except Exception as exc:                      # surface, do not hide
                md += [f"### {label}", "", f"**ERROR:** `{exc}`", ""]
                print(f"      !! {exc}")
                continue
            md += [f"### {label}", "", "```sql",
                   "\n".join(l for l in stmt.splitlines()
                             if not l.strip().startswith("--")).strip(), "```", ""]
            if df.empty:
                md += ["_no rows_", ""]
            else:
                shown = df.head(MAX_ROWS)
                md += [shown.to_markdown(index=False), ""]
                if len(df) > MAX_ROWS:
                    md += [f"_... {len(df) - MAX_ROWS} more rows_", ""]
        md += ["---", ""]

    # ---- the audit file is pass/fail, not a result set ----------------------
    md += ["## 06_data_quality_audit.sql - Data quality assertions", "",
           "Each check returns **zero rows when healthy**. Any output is a failure.", ""]
    print("\n>>> 06_data_quality_audit.sql")
    passed = failed = 0
    rows = []
    for title, stmt in split_statements((SQL / "06_data_quality_audit.sql").read_text()):
        name = ""
        for line in stmt.splitlines():
            m = re.match(r"^--\s*(CHECK\s+\d+[a-z]?\s+.*)$", line.strip())
            if m:
                name = m.group(1)
                break
        try:
            df = pd.read_sql_query(stmt, con)
        except Exception as exc:
            rows.append((name or "(check)", "ERROR", str(exc)[:60]))
            failed += 1
            continue
        if df.empty:
            rows.append((name or "(check)", "PASS", "0 rows returned"))
            passed += 1
        else:
            rows.append((name or "(check)", "**FAIL**", f"{len(df)} row(s): {df.iloc[0].to_dict()}"))
            failed += 1

    md += ["| Check | Result | Detail |", "|---|---|---|"]
    for name, res, detail in rows:
        md += [f"| {name} | {res} | {detail} |"]
    md += ["", f"**{passed} passed, {failed} failed.**", ""]
    print(f"    {passed} passed, {failed} failed")

    (SQL / "QUERY_RESULTS.md").write_text("\n".join(md) + "\n")
    print(f"\nWrote sql/QUERY_RESULTS.md")
    if failed:
        raise SystemExit(f"{failed} data-quality check(s) FAILED")


if __name__ == "__main__":
    print("Building warehouse...")
    con = build()
    run_reports(con)
    con.close()
